# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3813977c83858b0bd5e28d5fb163a7e25dfe657a631419e67e4667b726cace3a0efc98249c5fb82119107819ef2ec9c587331e5ae0b35ec06411474bcae8f6c

test:
  secret_key_base: 069165b60f2c049ef4346c2b50ad4ab9ddf6768aef3d435611ebfd01dc093ffc7d13c5b863f0aaccc1d73e7afdf556d74b8e57eb266af88781e4929ae5c9e245

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
